item {
    name: "plante_dans_pot_couchee",
    id: 1,
    display_name: "plante_dans_pot_couchee"
}
item {
    name: "plante_dans_pot_debout",
    id: 2,
    display_name: "plante_dans_pot_debout"
}
item {
    name: "plante_fragile_couchee",
    id: 3,
    display_name: "plante_fragile_couchee"
}
item {
    name: "plante_fragile_debout",
    id: 4,
    display_name: "plante_fragile_debout"
}
item {
    name: "pot_vide_couche",
    id: 5,
    display_name: "pot_vide_couche"
}
item {
    name: "pot_vide_debout",
    id: 6,
    display_name: "pot_vide_debout"
}
